'use strict';

/**
 * Champion Forge — Task Pool
 *
 * PVMER tasks: boss-based item_collection
 *   Each entry represents one boss / encounter. At event creation the resolver
 *   picks a random quantity from quantities[eventDifficulty] and injects it
 *   into descriptionTemplate, replacing {quantity}.
 *
 *   acceptableItems — list of notable drops used by admins when reviewing
 *   submissions to determine what qualifies as a valid drop from this boss.
 *
 * SKILLER tasks: XP milestones and skilling minigame completions.
 *   quantities[eventDifficulty] is a flat number injected into
 *   descriptionTemplate as {quantity}.
 *
 * Convention: task IDs start with 'pvm_' or 'skl_'
 */

// ---------------------------------------------------------------------------
// PVMER TASKS — item_collection (boss drops)
// ---------------------------------------------------------------------------

const PVM_INITIATE = [
  {
    id: 'pvm_init_abyssal_sire',
    label: 'Unsired Victory',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Abyssal Sire',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Abyssal Sire.',
    acceptableItems: [
      'Abyssal whip', 'Abyssal dagger', 'Bludgeon claw', 'Bludgeon spine',
      'Bludgeon axon', 'Abyssal head', 'Jar of souls', 'Unsired',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_init_kraken',
    label: 'Tentacle Tally',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Kraken',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Kraken.',
    acceptableItems: [
      'Trident of the seas (full)', 'Kraken tentacle', 'Pet kraken', 'Jar of dirt',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_init_dagannoth_kings',
    label: 'Triple Crown',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Dagannoth Kings',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Dagannoth Kings.',
    acceptableItems: [
      'Berserker ring', 'Archer ring', 'Seers ring', 'Warrior ring',
      'Dragon axe', 'Pet dagannoth prime', 'Pet dagannoth rex', 'Pet dagannoth supreme',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 4 },
    },
  },
  {
    id: 'pvm_init_barrows',
    label: 'Grave Situation',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Barrows',
    descriptionTemplate: 'Obtain {quantity} Barrows equipment piece(s) from the Barrows.',
    acceptableItems: [
      "Dharok's helm", "Dharok's platebody", "Dharok's platelegs", "Dharok's greataxe",
      "Guthan's helm", "Guthan's platebody", "Guthan's chainskirt", "Guthan's warspear",
      "Karil's coif", "Karil's leathertop", "Karil's leatherskirt", "Karil's crossbow",
      "Ahrim's hood", "Ahrim's robetop", "Ahrim's robeskirt", "Ahrim's staff",
      "Torag's helm", "Torag's platebody", "Torag's platelegs", "Torag's hammers",
      "Verac's helm", "Verac's brassard", "Verac's plateskirt", "Verac's flail",
    ],
    quantities: {
      casual:   { min: 1, max: 2 },
      standard: { min: 2, max: 4 },
      hardcore: { min: 4, max: 6 },
    },
  },
  {
    id: 'pvm_init_kbd',
    label: 'Here Be Dragons',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'King Black Dragon',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the King Black Dragon.',
    acceptableItems: [
      'Dragon pickaxe', 'Draconic visage', 'KBD heads', 'Prince black dragon',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_init_zilyana',
    label: "Holy Rollin'",
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Commander Zilyana',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Commander Zilyana.',
    acceptableItems: [
      'Saradomin sword', 'Armadyl crossbow', "Saradomin's light", 'Saradomin hilt', 'Pet zilyana',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_init_lizardman_shamans',
    label: 'Drop the Hammer',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Lizardman Shamans',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Lizardman Shamans.',
    acceptableItems: [
      'Dragon warhammer', "Xeric's talisman", 'Xerician fabric',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 1 },
      hardcore: { min: 1, max: 2 },
    },
  },
  {
    id: 'pvm_init_grotesque_guardians',
    label: 'Stone Cold',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Grotesque Guardians',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Grotesque Guardians.',
    acceptableItems: [
      'Black tourmaline core', 'Granite gloves', 'Granite hammer', 'Granite ring',
      'Jar of stone', 'Noon',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_init_cerberus',
    label: 'Down Boy',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Cerberus',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Cerberus.',
    acceptableItems: [
      'Primordial crystal', 'Pegasian crystal', 'Eternal crystal', 'Smouldering stone', 'Hellpuppy',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_init_thermonuclear',
    label: "Where There's Smoke",
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Thermonuclear Smoke Devil',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Thermonuclear Smoke Devil.',
    acceptableItems: [
      'Occult necklace', 'Smoke battlestaff', 'Dragon chainbody', 'Pet smoke devil',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_init_chaos_elemental',
    label: 'Absolute Chaos',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Chaos Elemental',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Chaos Elemental.',
    acceptableItems: [
      'Dragon pickaxe', "Chaos ele", 'Chaos elemental pet',
      "Dragon 2h sword", 'Odium shard', 'Malediction shard',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_init_scorpia',
    label: 'Sting Operation',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'initiate',
    boss: 'Scorpia',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Scorpia.',
    acceptableItems: [
      'Odium shard 1', 'Odium shard 2', 'Odium shard 3',
      'Malediction shard 1', 'Malediction shard 2', 'Malediction shard 3',
      "Scorpia's offspring",
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
];

const PVM_ADEPT = [
  {
    id: 'pvm_adept_graardor',
    label: 'Big High War God',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'General Graardor',
    descriptionTemplate: 'Obtain {quantity} drop(s) from General Graardor.',
    acceptableItems: [
      'Bandos chestplate', 'Bandos tassets', 'Bandos boots', 'Bandos hilt', 'Pet general graardor',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_kreearra',
    label: 'Bird of Prey',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: "Kree'arra",
    descriptionTemplate: "Obtain {quantity} drop(s) from Kree'arra.",
    acceptableItems: [
      'Armadyl helmet', 'Armadyl chestplate', 'Armadyl chainskirt', 'Armadyl hilt', "Pet kree'arra",
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_kril',
    label: 'Staff Meeting',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: "K'ril Tsutsaroth",
    descriptionTemplate: "Obtain {quantity} drop(s) from K'ril Tsutsaroth.",
    acceptableItems: [
      'Zamorakian spear', 'Staff of the dead', 'Zamorak hilt', "Pet k'ril tsutsaroth",
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_zulrah',
    label: 'Snake Charmer',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'Zulrah',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Zulrah.',
    acceptableItems: [
      'Tanzanite fang', 'Magic fang', 'Serpentine visage', 'Tanzanite mutagen',
      'Magma mutagen', 'Jar of swamp', 'Pet snakeling', 'Uncut onyx',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_vorkath',
    label: 'Undead Blues',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'Vorkath',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Vorkath.',
    acceptableItems: [
      "Vorkath's head", 'Draconic visage', 'Skeletal visage',
      'Dragonfire shield', 'Dragonfire ward', 'Vorki',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_demonic_gorillas',
    label: 'Ape Escape',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'Demonic Gorillas',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Demonic Gorillas.',
    acceptableItems: [
      'Zenyte shard', 'Ballista limbs', 'Ballista spring', 'Heavy frame', 'Light frame',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_nightmare',
    label: 'Sleep Deprived',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'The Nightmare',
    descriptionTemplate: 'Obtain {quantity} drop(s) from The Nightmare.',
    acceptableItems: [
      "Inquisitor's mace", "Inquisitor's great helm", "Inquisitor's hauberk",
      "Inquisitor's plateskirt", 'Nightmare staff', 'Eldritch orb',
      'Harmonised orb', 'Volatile orb', 'Little nightmare', 'Jar of dreams',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_gauntlet',
    label: 'Crystal Crusher',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'The Gauntlet',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Gauntlet.',
    acceptableItems: [
      'Crystal weapon seed', 'Crystal armour seed', 'Enhanced crystal weapon seed', 'Youngllef',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_alch_hydra',
    label: 'Chemical Reaction',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'Alchemical Hydra',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Alchemical Hydra.',
    acceptableItems: [
      "Hydra's claw", 'Hydra leather', "Hydra's eye", "Hydra's fang",
      "Hydra's heart", 'Hydra tail', 'Ikkle hydra', 'Jar of chemicals',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_corp',
    label: 'Sigil Seeker',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'Corporeal Beast',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Corporeal Beast.',
    acceptableItems: [
      'Spectral sigil', 'Arcane sigil', 'Elysian sigil', 'Divine sigil',
      'Spirit shield', 'Holy elixir', 'Pet dark core',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 1 },
      hardcore: { min: 1, max: 2 },
    },
  },
  {
    id: 'pvm_adept_kalphite_queen',
    label: "Queen's Gambit",
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'Kalphite Queen',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Kalphite Queen.',
    acceptableItems: [
      'Dragon chainbody', "Dragon 2h sword", 'KQ head', 'Kalphite princess',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_sarachnis',
    label: 'Caught in a Web',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'Sarachnis',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Sarachnis.',
    acceptableItems: [
      'Sarachnis cudgel', 'Giant egg sack (noted)', 'Jar of eyes', 'Sraracha',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_adept_callisto',
    label: 'Bear Market',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'adept',
    boss: 'Callisto',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Callisto.',
    acceptableItems: [
      'Tyrannical ring', 'Dragon pickaxe', 'Callisto cub',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
];

const PVM_MASTER = [
  {
    id: 'pvm_master_cox',
    label: 'Twisted Fate',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'Chambers of Xeric',
    descriptionTemplate: 'Obtain {quantity} unique(s) from the Chambers of Xeric.',
    acceptableItems: [
      'Twisted bow', 'Dragon claws', 'Elder maul', 'Ancestral hat',
      'Ancestral robe top', 'Ancestral robe bottom', 'Kodai insignia',
      "Dinh's bulwark", 'Dexterous prayer scroll', 'Arcane prayer scroll',
      'Twisted buckler', 'Dragon hunter crossbow', 'Olmlet',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_master_tob',
    label: 'Blood Money',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'Theatre of Blood',
    descriptionTemplate: 'Obtain {quantity} unique(s) from the Theatre of Blood.',
    acceptableItems: [
      'Scythe of vitur (uncharged)', 'Avernic defender hilt', 'Justiciar faceguard',
      'Justiciar chestguard', 'Justiciar legguards', 'Ghrazi rapier',
      'Sanguinesti staff (uncharged)', "Lil' zik",
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_master_toa',
    label: "Mummy's Loot",
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'Tombs of Amascut',
    descriptionTemplate: 'Obtain {quantity} unique(s) from the Tombs of Amascut.',
    acceptableItems: [
      "Tumeken's shadow (uncharged)", 'Masori mask', 'Masori body', 'Masori chaps',
      'Lightbearer', "Osmumten's fang", "Elidinis' ward", 'Thread of Elidinis', 'Cursed phalanx',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_master_inferno',
    label: 'Trial by Fire',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'The Inferno',
    descriptionTemplate: 'Earn {quantity} Infernal Cape(s) by completing the Inferno.',
    acceptableItems: ['Infernal cape', 'Jal-nib-rek'],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 1 },
      hardcore: { min: 1, max: 2 },
    },
  },
  {
    id: 'pvm_master_nex',
    label: 'Ancient Ambitions',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'Nex',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Nex.',
    acceptableItems: [
      'Torva full helm', 'Torva platebody', 'Torva platelegs',
      'Zaryte bow', 'Zaryte vambraces', 'Ancient hilt', 'Nihil horn', 'Nexling',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_master_phantom_muspah',
    label: 'Frozen in Fear',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'Phantom Muspah',
    descriptionTemplate: 'Obtain {quantity} drop(s) from the Phantom Muspah.',
    acceptableItems: [
      'Saturated heart', 'Venator shard', 'Ancient icon', 'Phantom muspah',
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_master_vardorvis',
    label: 'Axe to Grind',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'Vardorvis',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Vardorvis.',
    acceptableItems: [
      'Ultor vestige', 'Chromium ingot', 'Virtus mask', 'Virtus robe top', 'Virtus robe bottom',
      "Awakener's orb",
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_master_leviathan',
    label: 'Depths Below',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'The Leviathan',
    descriptionTemplate: 'Obtain {quantity} drop(s) from The Leviathan.',
    acceptableItems: [
      'Venator vestige', 'Chromium ingot', 'Virtus mask', 'Virtus robe top', 'Virtus robe bottom',
      "Awakener's orb",
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_master_whisperer',
    label: 'Hear No Evil',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'The Whisperer',
    descriptionTemplate: 'Obtain {quantity} drop(s) from The Whisperer.',
    acceptableItems: [
      'Bellator vestige', 'Chromium ingot', 'Virtus mask', 'Virtus robe top', 'Virtus robe bottom',
      "Awakener's orb",
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
  {
    id: 'pvm_master_duke_sucellus',
    label: 'Cold Case',
    type: 'item_collection',
    role: 'PVMER',
    difficulty: 'master',
    boss: 'Duke Sucellus',
    descriptionTemplate: 'Obtain {quantity} drop(s) from Duke Sucellus.',
    acceptableItems: [
      'Magus vestige', 'Chromium ingot', 'Virtus mask', 'Virtus robe top', 'Virtus robe bottom',
      "Awakener's orb",
    ],
    quantities: {
      casual:   { min: 1, max: 1 },
      standard: { min: 1, max: 2 },
      hardcore: { min: 2, max: 3 },
    },
  },
];

// ---------------------------------------------------------------------------
// SKILLER TASKS — XP milestones and skilling minigame completions
// quantities[eventDifficulty] is a flat number (not a range)
// ---------------------------------------------------------------------------

const SKL_INITIATE = [
  {
    id: 'skl_init_fishing_xp',
    label: 'Hooked In',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Earn {quantity} Fishing XP.',
    quantities: { casual: 200000, standard: 300000, hardcore: 400000 },
  },
  {
    id: 'skl_init_woodcutting_xp',
    label: 'Timber!',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Earn {quantity} Woodcutting XP.',
    quantities: { casual: 200000, standard: 300000, hardcore: 400000 },
  },
  {
    id: 'skl_init_mining_xp',
    label: 'Rock Solid',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Earn {quantity} Mining XP.',
    quantities: { casual: 200000, standard: 300000, hardcore: 400000 },
  },
  {
    id: 'skl_init_cooking_xp',
    label: 'Ready to Serve',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Earn {quantity} Cooking XP.',
    quantities: { casual: 200000, standard: 300000, hardcore: 400000 },
  },
  {
    id: 'skl_init_wintertodt',
    label: 'Cold Snap',
    type: 'minigame_completions',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Complete {quantity} Wintertodt rounds.',
    quantities: { casual: 10, standard: 15, hardcore: 20 },
  },
  {
    id: 'skl_init_tempoross',
    label: 'Fish Fight',
    type: 'minigame_completions',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Complete {quantity} Tempoross encounters.',
    quantities: { casual: 8, standard: 10, hardcore: 15 },
  },
  {
    id: 'skl_init_thieving_xp',
    label: 'Five-Finger Discount',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Earn {quantity} Thieving XP.',
    quantities: { casual: 200000, standard: 300000, hardcore: 400000 },
  },
  {
    id: 'skl_init_firemaking_xp',
    label: 'Light It Up',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Earn {quantity} Firemaking XP.',
    quantities: { casual: 200000, standard: 300000, hardcore: 400000 },
  },
  {
    id: 'skl_init_crafting_xp',
    label: 'Handmade',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Earn {quantity} Crafting XP.',
    quantities: { casual: 200000, standard: 300000, hardcore: 400000 },
  },
  {
    id: 'skl_init_fletching_xp',
    label: 'Strung Out',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Earn {quantity} Fletching XP.',
    quantities: { casual: 200000, standard: 300000, hardcore: 400000 },
  },
  {
    id: 'skl_init_pest_control',
    label: 'Pest Controller',
    type: 'minigame_completions',
    role: 'SKILLER',
    difficulty: 'initiate',
    descriptionTemplate: 'Complete {quantity} Pest Control games.',
    quantities: { casual: 15, standard: 20, hardcore: 30 },
  },
];

const SKL_ADEPT = [
  {
    id: 'skl_adept_agility_xp',
    label: 'In Stride',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Agility XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_herblore_xp',
    label: 'Brew Master',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Herblore XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_runecrafting_xp',
    label: 'Rune Factory',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Runecrafting XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_guardians_rift',
    label: 'Guardians of the Rift',
    type: 'minigame_completions',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Complete {quantity} Guardians of the Rift rounds.',
    quantities: { casual: 10, standard: 15, hardcore: 25 },
  },
  {
    id: 'skl_adept_farming_xp',
    label: 'Green Fingers',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Farming XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_hunter_xp',
    label: "Nature's Trapper",
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Hunter XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_construction_xp',
    label: 'Home Builder',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Construction XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_crafting_xp',
    label: 'Master Craftsman',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Crafting XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_smithing_xp',
    label: 'Anvil Pounder',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Smithing XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_zalcano',
    label: 'Zalcano Miner',
    type: 'minigame_completions',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Complete {quantity} Zalcano encounters.',
    quantities: { casual: 15, standard: 20, hardcore: 30 },
  },
  {
    id: 'skl_adept_woodcutting_xp',
    label: 'Lumber Baron',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Woodcutting XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_slayer_xp',
    label: 'Task Master',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Earn {quantity} Slayer XP.',
    quantities: { casual: 400000, standard: 500000, hardcore: 700000 },
  },
  {
    id: 'skl_adept_blast_furnace',
    label: 'Blast Furnace',
    type: 'minigame_completions',
    role: 'SKILLER',
    difficulty: 'adept',
    descriptionTemplate: 'Smelt {quantity} bars at the Blast Furnace.',
    quantities: { casual: 1000, standard: 1500, hardcore: 2500 },
  },
];

const SKL_MASTER = [
  {
    id: 'skl_master_agility_xp',
    label: 'Parkour Pro',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Earn {quantity} Agility XP.',
    quantities: { casual: 750000, standard: 1000000, hardcore: 1500000 },
  },
  {
    id: 'skl_master_runecrafting_xp',
    label: 'Soul of the Altar',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Earn {quantity} Runecrafting XP.',
    quantities: { casual: 750000, standard: 1000000, hardcore: 1500000 },
  },
  {
    id: 'skl_master_fishing_xp',
    label: 'Master Angler',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Earn {quantity} Fishing XP.',
    quantities: { casual: 750000, standard: 1000000, hardcore: 1500000 },
  },
  {
    id: 'skl_master_slayer_xp',
    label: 'Slayer Legend',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Earn {quantity} Slayer XP.',
    quantities: { casual: 750000, standard: 1000000, hardcore: 1500000 },
  },
  {
    id: 'skl_master_mining_xp',
    label: 'Deep Digger',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Earn {quantity} Mining XP.',
    quantities: { casual: 750000, standard: 1000000, hardcore: 1500000 },
  },
  {
    id: 'skl_master_sailing_xp',
    label: 'High Seas',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Earn {quantity} Sailing XP.',
    quantities: { casual: 750000, standard: 1000000, hardcore: 1500000 },
  },
  {
    id: 'skl_master_guardians_rift',
    label: 'Rift Veteran',
    type: 'minigame_completions',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Complete {quantity} Guardians of the Rift rounds.',
    quantities: { casual: 35, standard: 50, hardcore: 75 },
  },
  {
    id: 'skl_master_herblore_xp',
    label: 'Alchemist Supreme',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Earn {quantity} Herblore XP.',
    quantities: { casual: 750000, standard: 1000000, hardcore: 1500000 },
  },
  {
    id: 'skl_master_woodcutting_xp',
    label: 'Forest of the Fallen',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Earn {quantity} Woodcutting XP.',
    quantities: { casual: 750000, standard: 1000000, hardcore: 1500000 },
  },
  {
    id: 'skl_master_construction_xp',
    label: 'Grand Architect',
    type: 'xp_gain',
    role: 'SKILLER',
    difficulty: 'master',
    descriptionTemplate: 'Earn {quantity} Construction XP.',
    quantities: { casual: 750000, standard: 1000000, hardcore: 1500000 },
  },
];

// ---------------------------------------------------------------------------
// Exported structure — keyed by role then difficulty
// ---------------------------------------------------------------------------

const CW_OBJECTIVE_COLLECTIONS = {
  PVMER: {
    initiate: PVM_INITIATE,
    adept:    PVM_ADEPT,
    master:   PVM_MASTER,
  },
  SKILLER: {
    initiate: SKL_INITIATE,
    adept:    SKL_ADEPT,
    master:   SKL_MASTER,
  },
};

module.exports = { CW_OBJECTIVE_COLLECTIONS };
